networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  connectors-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-connectors-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${CONNECTOR_SERVICE_PORT}:${CONNECTOR_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
    restart: always